### ISSUE TITLE
VS code 1.25.1

### ISSUE THREAD

**Issue by floriandd2ba** [winbench/apps-default#5]
Hi,

a new version is out. It seems, the links are changed.
With this change in apps.md it works for me (Onlx 64bit tested):
### Visual Studio Code

* Version: 1.25.1
* Url32Bit: <https://go.microsoft.com/fwlink/?LinkID=623231>
* Url64Bit: <https://go.microsoft.com/fwlink/?Linkid=850641>
* ArchiveName32Bit: `VSCode-win32-ia32-$:Version$.zip`
* ArchiveName64Bit: `VSCode-win32-x64-$:Version$.zip`

P.S.: THX for PlantUML

Sunny sunday
Florian

**Comment by mastersign** [comment]
The URLs for Visual Studio Code always point to the latest version. This is true for some more apps and is the case when the `Version` app property is missing or is set to `latest`.

To upgrade an app where the URL alway points to the latest release, open the setup dialog, and right-click the app, then choose _Upgrade_.

**Hint:** To upgrade all apps where no specific version information exists or where a version range is defined (e.g. some npm packages) use the menu in the setup dialog _Setup_ &rarr; _Upgrade Apps_.
